export const FETCH_TOKEN = 'FETCH_TOKEN';
export const FETCH_TOKEN_FULFILLED = "FETCH_TOKEN_FULFILLED";
export const FETCH_TOKEN_REJECTED = "FETCH_TOKEN_REJECTED";

export const SET_ARRIVAL_LOCATION = 'SET_ARRIVAL_LOCATION';
export const SET_DEPARTURE_LOCATION = 'SET_DEPARTURE_LOCATION';

export const FETCH_JOURNEY = 'FETCH_JOURNEY'
export const FETCH_JOURNEY_FULFILLED = 'FETCH_JOURNEY_FULFILLED'
export const FETCH_JOURNEY_REJECTED = 'FETCH_JOURNEY_REJECTED'

export const SELECT_ITINERARY = 'SELECT_ITINERARY'

export const SELECT_LINE = 'SELECT_LINE'

export const SELECT_STOP = 'SELECT_STOP'

export const CLEAR_LOCATION = 'CLEAR_LOCATION';