export const FETCH_TOKEN = 'FETCH_TOKEN';
export const FETCH_TOKEN_FULFILLED = "FETCH_TOKEN_FULFILLED";
export const FETCH_TOKEN_REJECTED = "FETCH_TOKEN_REJECTED";

export const SET_ARRIVAL_LOCATION = 'SET_ARRIVAL_LOCATION';
export const SET_ARRIVAL_LOCATION_FULFILLED = 'SET_ARRIVAL_LOCATION_FULFILLED';
export const SET_ARRIVAL_LOCATION_REJECTED = 'SET_ARRIVAL_LOCATION_REJECTED';

export const SET_DEPARTURE_LOCATION = 'SET_DEPARTURE_LOCATION';
export const SET_DEPARTURE_LOCATION_FULFILLED = 'SET_DEPARTURE_LOCATION_FULFILLED';
export const SET_DEPARTURE_LOCATION_REJECTED = 'SET_DEPARTURE_LOCATION_REJECTED';

export const CLEAR_LOCATION = 'CLEAR_LOCATION';